DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'game') THEN
        CREATE SCHEMA game;
    END IF;
END $EF$;


CREATE TABLE game.character (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    level integer NOT NULL,
    creation_date timestamp with time zone NOT NULL,
    guild text,
    traits jsonb,
    CONSTRAINT "PK_character" PRIMARY KEY (id)
);


CREATE TABLE game.archer (
    id integer NOT NULL,
    precision double precision NOT NULL,
    has_pet boolean NOT NULL,
    CONSTRAINT "PK_archer" PRIMARY KEY (id),
    CONSTRAINT "FK_archer_character_id" FOREIGN KEY (id) REFERENCES game.character (id) ON DELETE CASCADE
);


CREATE TABLE game.cleric (
    id integer NOT NULL,
    deity text NOT NULL,
    healing_points integer NOT NULL,
    CONSTRAINT "PK_cleric" PRIMARY KEY (id),
    CONSTRAINT "FK_cleric_character_id" FOREIGN KEY (id) REFERENCES game.character (id) ON DELETE CASCADE
);


CREATE TABLE game.mage (
    id integer NOT NULL,
    mana integer NOT NULL,
    main_element text NOT NULL,
    CONSTRAINT "PK_mage" PRIMARY KEY (id),
    CONSTRAINT "FK_mage_character_id" FOREIGN KEY (id) REFERENCES game.character (id) ON DELETE CASCADE
);


CREATE TABLE game.warrior (
    id integer NOT NULL,
    main_weapon text NOT NULL,
    fury integer NOT NULL,
    CONSTRAINT "PK_warrior" PRIMARY KEY (id),
    CONSTRAINT "FK_warrior_character_id" FOREIGN KEY (id) REFERENCES game.character (id) ON DELETE CASCADE
);


