// <auto-generated />
using System;
using System.Text.Json.Nodes;
using GestorHeroesRPG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorHeroesRPG.Migrations
{
    [DbContext(typeof(GameDBContext))]
    partial class GameDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("game")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorHeroesRPG.Model.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Gremio")
                        .HasColumnType("text")
                        .HasColumnName("guild");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<JsonNode>("Rasgos")
                        .HasColumnType("jsonb")
                        .HasColumnName("traits");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("character", "game");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GestorHeroesRPG.Model.Arquero", b =>
                {
                    b.HasBaseType("GestorHeroesRPG.Model.Personaje");

                    b.Property<double>("Precision")
                        .HasColumnType("double precision")
                        .HasColumnName("precision");

                    b.Property<bool>("TieneMascota")
                        .HasColumnType("boolean")
                        .HasColumnName("has_pet");

                    b.ToTable("archer", "game");
                });

            modelBuilder.Entity("GestorHeroesRPG.Model.Clerigo", b =>
                {
                    b.HasBaseType("GestorHeroesRPG.Model.Personaje");

                    b.Property<string>("Divinidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deity");

                    b.Property<int>("PuntosSanacion")
                        .HasColumnType("integer")
                        .HasColumnName("healing_points");

                    b.ToTable("cleric", "game");
                });

            modelBuilder.Entity("GestorHeroesRPG.Model.Guerrero", b =>
                {
                    b.HasBaseType("GestorHeroesRPG.Model.Personaje");

                    b.Property<string>("ArmaPrincipal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("main_weapon");

                    b.Property<int>("Furia")
                        .HasColumnType("integer")
                        .HasColumnName("fury");

                    b.ToTable("warrior", "game");
                });

            modelBuilder.Entity("GestorHeroesRPG.Model.Mago", b =>
                {
                    b.HasBaseType("GestorHeroesRPG.Model.Personaje");

                    b.Property<string>("ElementoPrincipal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("main_element");

                    b.Property<int>("Mana")
                        .HasColumnType("integer")
                        .HasColumnName("mana");

                    b.ToTable("mage", "game");
                });

            modelBuilder.Entity("GestorHeroesRPG.Model.Arquero", b =>
                {
                    b.HasOne("GestorHeroesRPG.Model.Personaje", null)
                        .WithOne()
                        .HasForeignKey("GestorHeroesRPG.Model.Arquero", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorHeroesRPG.Model.Clerigo", b =>
                {
                    b.HasOne("GestorHeroesRPG.Model.Personaje", null)
                        .WithOne()
                        .HasForeignKey("GestorHeroesRPG.Model.Clerigo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorHeroesRPG.Model.Guerrero", b =>
                {
                    b.HasOne("GestorHeroesRPG.Model.Personaje", null)
                        .WithOne()
                        .HasForeignKey("GestorHeroesRPG.Model.Guerrero", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorHeroesRPG.Model.Mago", b =>
                {
                    b.HasOne("GestorHeroesRPG.Model.Personaje", null)
                        .WithOne()
                        .HasForeignKey("GestorHeroesRPG.Model.Mago", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
